\." $Id$
.\"
.TH DIGI.CONF 1 "Release 0.1.4" "LLNL" "DIGI.CONF"

.SH NAME
digi.conf \- configuration file format for digi

.SH DESCRIPTION
This file is read by
.B digi
and contains a list of nodes, one per line, along with the tty line 
from which power status may be read.  A typical line might be:
.LP
.RS
tux17 /dev/ttyD17
.RE
.LP


.SH "FILES"
$powermandir/etc/digi.conf

.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's Alpha and
Intel Linux clusters.

.SH "SEE ALSO"
digi(1), pm(1)

