\." $Id$
.\"
.TH ICEBOX.CONF 1 "Release 0.1.7" "LLNL" "ICEBOX.CONF"

.SH NAME
icebox.conf \- configuration file format for icebox

.SH DESCRIPTION
This file is read by
.B icebox
and contains a list of nodes, one per line, along with the tty line, 
ice box number, and port number from which power status may be read.  
A typical line might be:
.LP
.RS
tux17 /dev/ttyS0 0 0
.RE
.LP


.SH "FILES"
$powermandir/etc/icebox.conf

.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's 
Intel Linux clusters.

.SH "SEE ALSO"
icebox(1), pm(1)

