\." $Id$
.\"
.TH PM 1 "Release 0.1.9" "LLNL" "PM"

.SH NAME
pm \- issue power monitoring queries and power control commands

.SH SYNOPSIS
.B pm
.I "[-options]"
.LP
.B pm
.I "[-options] [command]"

.SH DESCRIPTION
.B pm
(for PowerMan) allows power monitoring and power management on a 
cluster of nodes to be performed independent of the underlying hardware.
Options are described in TARGET NODE LIST OPTIONS and OTHER OPTIONS below.
.LP
For a command in 
.I [on, off, reset]
.B pm
will power on, power off, or reset, respectively, the target nodes.  If
none of the above commands is provided 
.B pm
queries the target nodes for their power status and prints the names of 
those that are on, one per line (but see -t and -r below).
.LP
.B pm 
operates in conjuction with one or more underlying, hardware-specific
modules, each of wich conforms to a uniform interface.    
.B pm 
runs on a management workstation equipped with power monitoring and 
control hardware.
.LP

.SH TARGET NODE LIST OPTIONS
.I "-w host,host,..."
Target the specified nodes.  No spaces are allowed in the comma-separated
list.  Substituting the "-" character for the list causes the target nodes
to be read from stdin, one per line.
.LP
.I "-a"
Target "all" nodes in the cluster.  
.B pm
determines the list of nodes in the cluster from the configuration file
(see FILES below).

.SH OTHER OPTIONS
.LP
.I "-c configfile"
Provide an alternate name or location for the configuration file.
.LP
.I "-f number"
Set the maximum concurrency for underlying utilities.  The default is 256.
.I "-l powermandir"
Provide an alternate location for the PowerMan libraries.
.I "-L"
Log interactions to /tmp/powerman.conf.  N.B. Only the icebox module logs
its interactions at this time.
.LP
.I "-q"
be quiet, i.e. don't print error messages.
.LP
.I "-r"
reverse, i.e. print nodes that are off rather than on
.LP
.I "-t"
query the CPU temperature(s), if available, rather than the power status.
Output the node name followed by the temperature for the target nodes, one
node per line.  N.B.  This is only supported by the icebox module.  

.SH "FILES"
/usr/bin/pm
.br
/etc/powerman.conf
.br
$powermandir/<module>.py
.br
$powermandir/<utility-support>
.br

.SH "ENVIRONMENT"
The environment variable
.B POWERMANDIR
gives an alternative location for the powerman libraries and hardware specific
modules, overriding the default "/usr/lib/powerman".  The "-l" option, 
in turn, overrides the environment variable.  Similarly,
.B POWERMANCONF
gives an alternative file for cluster configuration details.  It 
overrides the default "/etc/powerman.conf" and is, in turn, overridden 
by the "-c" option.   If the 
.B W_COL
(working collective) environment variable is set to a file name then 
the list of nodes is taken from that file, one per line.  "-a",
and "-w" override the working collective envirnment variable.  

.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's Alpha and
Intel Linux clusters.  Originally released for LLNL-only use pending 
review for distribution under GPL.

.SH "LIMITATIONS"
Most of the code for this utility is written in Python, and as such is
probably portable to other operating systems and hardware.  Some
localization may be required.  
.SH "SEE ALSO"
powerman.conf(5)
