\."#################################################################
\."$Id$
\."by Andrew C. Uselton <uselton2@llnl.gov> 
\."#################################################################
\."  Copyright (C) 2001-2002 The Regents of the University of California.
\."  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
\."  Written by Andrew Uselton (uselton2@llnl.gov>
\."  UCRL-CODE-2002-008.
\."  
\."  This file is part of PowerMan, a remote power management program.
\."  For details, see <http://www.llnl.gov/linux/powerman/>.
\."  
\."  PowerMan is free software; you can redistribute it and/or modify it under
\."  the terms of the GNU General Public License as published by the Free
\."  Software Foundation; either version 2 of the License, or (at your option)
\."  any later version.
\."  
\."  PowerMan is distributed in the hope that it will be useful, but WITHOUT 
\."  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
\."  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
\."  for more details.
\."  
\."  You should have received a copy of the GNU General Public License along
\."  with PowerMan; if not, write to the Free Software Foundation, Inc.,
\."  59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
\."#################################################################
.\"
.TH POWERMAN.CONF 1 "Release 1.0.0" "LLNL" "POWERMAN.CONF"

.SH NAME
powerman.conf \- configuration file format for PowerMan

.SH DESCRIPTION
This file is read by
.B powermand
and contains the name of the cluster under power management and a list
of nodes in the cluster.  The format for this configuration file has
changed entirely since the following was written.  I'll update it 
shortly.  For a cluster named "tux" the name appears in 
the configuration file as:
.LP
.RS
cluster tux
.RE
.LP
Nodes appear, one per line, with a name, a power monitoring function, 
and a power control function.  A typical node in the cluster using digi
power monitoring and etherwake power control might look like this:
.LP
.RS
node tux17 {digi /dev/ttyD0} {etherwake 00:11:22:33:44:55}
.RE
.LP
The hardware detail block contained in the curly braces is hardware
dependent.  In the case that power monitoring and power management are
carried out by the same hardware (as in the 
.I icebox
hardware) one may include a single hardware detail block.  If both are
present then the monitoring block comes before the control block.
Each block begins with the name of the hardware (which must correspond
to the 
.I Python 
module's name in /usr/lib/powerman) and includes a list of details
needed by that module.  The source RPM for powerman contains examples
of configurations for each of the supported types. 


.SH "FILES"
/etc/powerman.conf

.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's Alpha and
Intel Linux clusters.

.SH "SEE ALSO"
pm(1)

