\."#################################################################
\."$Id$
\."by Andrew C. Uselton <uselton2@llnl.gov> 
\."#################################################################
\."  Copyright (C) 2001-2002 The Regents of the University of California.
\."  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
\."  Written by Andrew Uselton (uselton2@llnl.gov>
\."  UCRL-CODE-2002-008.
\."  
\."  This file is part of PowerMan, a remote power management program.
\."  For details, see <http://www.llnl.gov/linux/powerman/>.
\."  
\."  PowerMan is free software; you can redistribute it and/or modify it under
\."  the terms of the GNU General Public License as published by the Free
\."  Software Foundation; either version 2 of the License, or (at your option)
\."  any later version.
\."  
\."  PowerMan is distributed in the hope that it will be useful, but WITHOUT 
\."  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
\."  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
\."  for more details.
\."  
\."  You should have received a copy of the GNU General Public License along
\."  with PowerMan; if not, write to the Free Software Foundation, Inc.,
\."  59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
\."#################################################################
.\"
.TH PowerMan 1 "Release 1.0.0" "LLNL" "PowerMan"

.SH NAME
powermand \- power control and monitoring daemon

.SH SYNOPSIS
.B powermand
.I "[-options]"
.LP

.SH DESCRIPTION
.B powermand
provides power monitoring and power management on a 
cluster of nodes.  

.SH OPTIONS
.LP
.I "-c configfile"
.br
.I "--config_file configfile"
.br
Provide an alternate name or location for the configuration file.  
Configuration files are usually located in 
.I /etc/powerman/powerman.conf
though they can be anywhere.  
.I configfile
must be an absolute path.
.LP
.I "-d"
.br
.I "--dont_daemonize"
.br
For debugging it may be helpfull to suppress the "daemonization".
.LP
.I "-h"
.br
.I "--help"
.br
Provide a synopsis of the command options.
.LP
.I "-k"
.br
.I "--kill"
.br
Send a 
.I SIGTERM
to a running daemon, causing it to abort.  
.LP
.I "-L"
.br
.I "--license"
.br
Print license information about 
.B PowerMan
and exit.
.LP
.I "-r"
.br
.I "--reread_config"
.br
Send a 
.I SIGHUP 
to a running daemon causing it reread its config file.
.LP
.I "-V"
.br
.I "--version"
.br
Print the version of the program and exit.

.SH "FILES"
/usr/bin/powermand
.br
/usr/bin/powerman
.br
/etc/powerman/powerman.conf
.br

.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's Linux 
clusters.  This software is open source and distributed under
the terms of the Gnu GPL.  

.SH "SEE ALSO"
powerman(1) powerman.conf(5)
