\."#################################################################
\."$Id$
\."by Andrew C. Uselton <uselton2@llnl.gov> 
\."#################################################################
\."  Copyright (C) 2001-2002 The Regents of the University of California.
\."  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
\."  Written by Andrew Uselton (uselton2@llnl.gov>
\."  UCRL-CODE-2002-008.
\."  
\."  This file is part of PowerMan, a remote power management program.
\."  For details, see <http://www.llnl.gov/linux/powerman/>.
\."  
\."  PowerMan is free software; you can redistribute it and/or modify it under
\."  the terms of the GNU General Public License as published by the Free
\."  Software Foundation; either version 2 of the License, or (at your option)
\."  any later version.
\."  
\."  PowerMan is distributed in the hope that it will be useful, but WITHOUT 
\."  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
\."  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
\."  for more details.
\."  
\."  You should have received a copy of the GNU General Public License along
\."  with PowerMan; if not, write to the Free Software Foundation, Inc.,
\."  59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
\."#################################################################
.\"
.TH PowerMan 1 "Release 1.0.0" "LLNL" "PowerMan"

.SH NAME
powerman \- power on/off/cycle nodes

.SH SYNOPSIS
.B powerman
.I "[-options] [targets]"
.br
.B pm
.I "[-options] [targets]"
.br
.B on
.I "[targets]"
.br
.B off
.I "[targets]"

.SH DESCRIPTION
.B powerman
provides power management on a cluster of nodes.  It performs operations
such as power on, power off, power cycle, and hardware reset on nodes.
Nodes are typically node hostnames which are mapped to plugs on remote 
power control (RPC) units in
.I powerman.conf(5).
.br
.SH OPTIONS
.LP
.I "-r"
.I "--reset"
Reset targets.
.LP
.I "-c"
.I "--cycle"
Power cycle targets.
.LP
.I "-1"
.I "--on"
Power on targets.
.LP
.I "-0"
.I "--off"
Power off targets.
.LP
.I "-l"
.I "--list"
List available targets.  If possible, output will be compressed into
a host range (see HOST RANGES below).
.LP
.I "-z"
.I "--report [host range]"
Report power status of all targets (or if host range is provided,
only obtain status for those targets).  Status is not cached; each
time this option is used, powermand contacts the appropriate RPC's.

.SH "HOST RANGES"
As noted in sections above,
.B powerman
accepts ranges of hostnames in
the general form: prefix[n-m,l-k,...], where n < m and l < k, etc.,
as an alternative to explicit lists of hosts.  This form should not
be confused with regular expression character classes (also denoted
by ``[]''). For example, foo[19] does not represent foo1 or foo9, but
rather represents a degenerate range: foo19.

This range syntax is meant
only as a convenience on clusters with a prefixNN naming convention and
specification of ranges should not be considered necessary -- the list
foo1,foo9 could be specified as such, or by the range foo[1,9].

Some examples of range usage follow:

Power on hosts foo01,foo02,...,foo05
    powerman --on foo[01-05]

Power on hosts foo7,foo9,foo10
    powerman --on foo[7,9-10]

Power on foo0,foo4,foo5
    powerman --on foo[0-5]

.SH "FILES"
/usr/sbin/powermand
.br
/usr/bin/powerman
.br
/usr/bin/pm
.br
/usr/bin/on
.br
/usr/bin/off
.br
/etc/powerman/powerman.conf
.br
/etc/powerman/*.dev
.br

.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's Linux 
clusters.  This software is open source and distributed under
the terms of the Gnu GPL.  

.SH "SEE ALSO"
powermand(1) powerman.conf(5)
