\."#################################################################
\."$Id$
\."by Andrew C. Uselton <uselton2@llnl.gov> 
\."#################################################################
\."  Copyright (C) 2001-2002 The Regents of the University of California.
\."  Produced at Lawrence Livermore National Laboratory (cf, DISCLAIMER).
\."  Written by Andrew Uselton (uselton2@llnl.gov>
\."  UCRL-CODE-2002-008.
\."  
\."  This file is part of PowerMan, a remote power management program.
\."  For details, see <http://www.llnl.gov/linux/powerman/>.
\."  
\."  PowerMan is free software; you can redistribute it and/or modify it under
\."  the terms of the GNU General Public License as published by the Free
\."  Software Foundation; either version 2 of the License, or (at your option)
\."  any later version.
\."  
\."  PowerMan is distributed in the hope that it will be useful, but WITHOUT 
\."  ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or 
\."  FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License 
\."  for more details.
\."  
\."  You should have received a copy of the GNU General Public License along
\."  with PowerMan; if not, write to the Free Software Foundation, Inc.,
\."  59 Temple Place, Suite 330, Boston, MA  02111-1307  USA.
\."#################################################################
.\"
.TH POWERMAN.CONF 1 "Release 1.0" "LLNL" "POWERMAN.CONF"

.SH NAME
powerman.conf \- configuration file for PowerMan

.SH DESCRIPTION
The powerman.conf file typically includes one or more of the remote power 
controller (RPC) device files provided in the /etc/powerman directory; 
sets a few global options; 
instantiates RPC devices with unique names, hostnames, and ports;  
and maps node names to RPC's and plug numbers.
.SH EXAMPLE
The following example is a 16-node cluster that uses two 8-plug
Baytech RPC-3 remote power controllers.
.LP
.nf \fI
include "/etc/powerman/baytech.dev"  # include def for "baytech" RPC

tcpwrappers yes                      # enable TCP wrappers

# Alias example - alias can be used in target specifications
alias "pengra_service" "pengra[0-1]"
alias "pengra_compute" "pengra[2-15]"

# Power controller: device <name> <type> <hostname:port> [<flags>]
device "pow0" "baytech" "pow0:23"  # instantiate pow0
device "pow1" "baytech" "pow1:23"  # instantiate pow1

# Plugs: node <name> <device> [<plug>]
node "pengra0" "pow0" "1"    # map pengra0 to pow0 plug 1
node "pengra1" "pow0" "2"    # map pengra0 to pow0 plug 2
node "pengra2" "pow0" "3"    # ...
node "pengra3" "pow0" "4"
node "pengra4" "pow0" "5"
node "pengra5" "pow0" "6"
node "pengra6" "pow0" "7"
node "pengra7" "pow0" "8"
node "pengra8" "pow1" "1"    # map pengra8 to pow1 plug 1
node "pengra9" "pow1" "2"    # map pengra9 to pow1 plug 2
node "pengra10" "pow1" "3"   # ...
node "pengra11" "pow1" "4"
node "pengra12" "pow1" "5"
node "pengra13" "pow1" "6"
node "pengra14" "pow1" "7"
node "pengra15" "pow1" "8" \fR
.fi
.SH "FILES"
/etc/powerman/powerman.conf
.br
/etc/powerman/*.dev
.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's Linux 
clusters.  This software is open source and distributed under
the terms of the Gnu GPL.  
.SH "SEE ALSO"
powermand(1) powerman(1)

