\." $Id$
.\"
.TH WTI 1 "Release 0.1.5" "LLNL" "WTI"

.SH NAME
wti \- low-level power control

.SH SYNOPSIS
.B wti
.I "[-options] [command]"

.SH DESCRIPTION
.B wti
is a low level utility in support of the PowerMan power management 
program.  It communicates with a target node via a tty.
For a command in 
.I [on, off, reset]
.B wti
will send a specially formatted command to a port on the tty specific
to each of the target nodes.
.B wti
conforms to the PowerMan power monitoring interface.  One will generally
prefer to use 
.B pm
rather than this low-level utility, but its use is not forbidden to 
root priveleged users.  Unlike toggling ethernet wake-on-LAN it is 
safe to send an "on" command to an on node and vice-versa.  
Options are described in TARGET NODE LIST OPTIONS and OTHER OPTIONS below.
.LP
The POWERMAN environment variable, if set, identifies an alternate 
directory fo the PowerMan libraries and configuration files.

.SH TARGET NODE LIST OPTIONS
.I "-w host,host,..."
Target the specified nodes.  No spaces are allowed in the comma-separated
list.  Substituting the "-" character for the list causes the target nodes
to be read from stdin, one per line.
.LP
.I "-a"
Target "all" nodes in the cluster.  
.B wti
determines the list of nodes in the cluster from the configuration file
(see FILES below).

.SH OTHER OPTIONS
.LP
.I "-c configfile"
Provide an alternate name or location for the configuration file.
.LP
.I "-f number"
Set the maximum concurrency, currently unused.  
.I "-l powermandir"
Provide an alternate location for the PowerMan libraries.
.LP
.I "-v"
be verbose, i.e. print error messages rather than dying quietly.

.SH "FILES"
$powermandir/bin/wti
.br
$powermandir/etc/wti.conf
.br

.SH "ORIGIN"
Developed by Andrew  Uselton <useton2@llnl.gov> on LLNL's Alpha and
Intel Linux clusters.

.SH "SEE ALSO"
pm(1), digi(1), etherwake(1), rmc(1), wti.conf(5)

