#!/bin/sh

./mkconf.pl 1024 $PATH_ETC >t04.conf || exit 1

$PATH_POWERMAN -S $PATH_POWERMAND -C t04.conf -q >t04.out 2>t04.err || exit 1
test `wc -l <t04.err` = 64 || exit 1
diff t04.out t04.exp >t04.diff
