#!/bin/sh
# 1 vpcd instance, 16 nodes, query status
# This time no _all commands (so query will be 16 distinct commands)
TEST=t07
$PATH_POWERMAN -S $PATH_POWERMAND -C $TEST.conf -q >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out $TEST.exp >$TEST.diff
