#!/bin/sh
# 1 vpcd instance, 16 nodes, no _all commands, query status
# Add telemetry option.
TEST=t08
$PATH_POWERMAN -S $PATH_POWERMAND -C $TEST.conf -T -q >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out $TEST.exp >$TEST.diff
