#!/bin/sh
TEST=t11
$PATH_POWERMAN -S $PATH_POWERMAND -C ${TEST_BUILDDIR}/test.conf \
  -q -1 t4 -q -0 t4 -q -c t5 -q >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out ${TEST_SRCDIR}/$TEST.exp >$TEST.diff
