#!/bin/sh
# 1 vpcd instance, 16 nodes, single command with old style target spec
TEST=t12
$PATH_POWERMAN -S $PATH_POWERMAND -C $TEST.conf -q t1  >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out $TEST.exp >$TEST.diff
