on:      
off:     t[0-159]
unknown: 
Command completed successfully
on:      t[0,20,40,60,80,100,120,140]
off:     t[1-19,21-39,41-59,61-79,81-99,101-119,121-139,141-159]
unknown: 
Command completed successfully
on:      t[0,20,40,60,80,100,120,140]
off:     t[1-19,21-39,41-59,61-79,81-99,101-119,121-139,141-159]
unknown: 
Command completed successfully
on:      
off:     t[0-159]
unknown: 
Command completed successfully
on:      t[0-159]
off:     
unknown: 
Command completed successfully
on:      t[0-159]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-159]
unknown: 
