#!/bin/sh
TEST=t25
$PATH_POWERMAN -S $PATH_POWERMAND -C ${TEST_BUILDDIR}/$TEST.conf \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    -c t1 -c t1 -c t1 -c t1 \
    >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out ${TEST_SRCDIR}/$TEST.exp >$TEST.diff
