#!/bin/sh
TEST=t31
$PATH_POWERMAN -Y -S $PATH_POWERMAND -C ${TEST_BUILDDIR}/$TEST.conf \
    -q -1 t0 \
    -q -c t0 \
    -q -0 t0 \
    -q -1 t[0-9] \
    -q -c t[0-9] \
    -q -0 t[0-9] \
    -q -t >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out ${TEST_SRCDIR}/$TEST.exp >$TEST.diff
