#!/bin/sh
TEST=t31
$PATH_POWERMAN -Y -S $PATH_POWERMAND -C $TEST.conf \
    -q -n -1 t0 \
    -q -n -c t0 \
    -q -n -0 t0 \
    -q -n -1 t[0-9] \
    -q -n -c t[0-9] \
    -q -n -0 t[0-9] \
    -q -n -t >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out $TEST.exp >$TEST.diff
