on:      
off:     t[0-9]
unknown: 
on:      
off:     t[0-9]
unknown: 
Command completed successfully
on:      t0
off:     t[1-9]
unknown: 
on:      t0
off:     t[1-9]
unknown: 
Command completed successfully
on:      t0
off:     t[1-9]
unknown: 
on:      t0
off:     t[1-9]
unknown: 
Command completed successfully
on:      
off:     t[0-9]
unknown: 
on:      
off:     t[0-9]
unknown: 
Command completed successfully
on:      t[0-9]
off:     
unknown: 
on:      t[0-9]
off:     
unknown: 
Command completed successfully
on:      t[0-9]
off:     
unknown: 
on:      t[0-9]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-9]
unknown: 
on:      
off:     t[0-9]
unknown: 
t0: 73,0,0,0
t1: 74,0,0,0
t2: 75,0,0,0
t3: 76,0,0,0
t4: 77,0,0,0
t5: 78,0,0,0
t6: 79,0,0,0
t7: 80,0,0,0
t8: 81,0,0,0
t9: 82,0,0,0
