on:      
off:     t[0-9]
unknown: 
on:      
off:     t[0-9]
unknown: 
Command completed successfully
on:      t0
off:     t[1-9]
unknown: 
on:      t0
off:     t[1-9]
unknown: 
Command completed successfully
on:      t0
off:     t[1-9]
unknown: 
on:      t0
off:     t[1-9]
unknown: 
Command completed successfully
on:      
off:     t[0-9]
unknown: 
on:      
off:     t[0-9]
unknown: 
Command completed successfully
on:      t[0-9]
off:     
unknown: 
on:      t[0-9]
off:     
unknown: 
Command completed successfully
on:      t[0-9]
off:     
unknown: 
on:      t[0-9]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-9]
unknown: 
Command completed successfully
on:      t0
off:     t[1-9]
unknown: 
Command completed successfully
on:      
off:     t[0-9]
unknown: 
Command completed successfully
on:      t[0-9]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-9]
unknown: 
on:      
off:     t[0-9]
unknown: 
on:      
off:     t[0-9]
unknown: 
t0: 73:
t1: 74:
t2: 75:
t3: 76:
t4: 77:
t5: 78:
t6: 79:
t7: 80:
t8: 81:
t9: 82:
