on:      
off:     t[0-63]
unknown: 
Command completed successfully
on:      t[0,8,16,24,32,40,48,56]
off:     t[1-7,9-15,17-23,25-31,33-39,41-47,49-55,57-63]
unknown: 
Command completed successfully
on:      t[0,8,16,24,32,40,48,56]
off:     t[1-7,9-15,17-23,25-31,33-39,41-47,49-55,57-63]
unknown: 
Command completed successfully
on:      
off:     t[0-63]
unknown: 
Command completed successfully
on:      
off:     t[0-63]
unknown: 
Command completed successfully
on:      t[0-63]
off:     
unknown: 
Command completed successfully
on:      t[0-63]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-63]
unknown: 
Command completed successfully
on:      
off:     t[0-63]
unknown: 
