on:      
off:     t[0-19]
unknown: 
Command completed successfully
on:      t0
off:     t[1-19]
unknown: 
Command completed successfully
on:      t0
off:     t[1-19]
unknown: 
Command completed successfully
on:      
off:     t[0-19]
unknown: 
Command completed successfully
on:      t[0-19]
off:     
unknown: 
Command completed successfully
on:      t[0-19]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-19]
unknown: 
