on:      
off:     t[0-63]
unknown: 
Command completed successfully
on:      t[0,16,32,48]
off:     t[1-15,17-31,33-47,49-63]
unknown: 
Command completed successfully
on:      t[0,16,32,48]
off:     t[1-15,17-31,33-47,49-63]
unknown: 
Command completed successfully
on:      
off:     t[0-63]
unknown: 
Command completed successfully
on:      t[0-63]
off:     
unknown: 
Command completed successfully
on:      t[0-63]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-63]
unknown: 
