on:      
off:     t0
unknown: t1
Command completed successfully
on:      t0
off:     
unknown: t1
Command completed successfully
on:      t0
off:     
unknown: t1
Command completed successfully
on:      
off:     t0
unknown: t1
Command completed successfully
on:      t0
off:     
unknown: t1
Command completed successfully
on:      t0
off:     
unknown: t1
Command completed successfully
on:      
off:     t0
unknown: t1
