on:      
off:     t[0-7]
unknown: 
Command completed successfully
on:      t0
off:     t[1-7]
unknown: 
Command completed successfully
on:      t0
off:     t[1-7]
unknown: 
Command completed successfully
on:      
off:     t[0-7]
unknown: 
Command completed successfully
on:      t[0-7]
off:     
unknown: 
Command completed successfully
on:      t[0-7]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-7]
unknown: 
