on:      
off:     t[0-1]
unknown: 
Command completed successfully
on:      t[0-1]
off:     
unknown: 
Command completed successfully
on:      t[0-1]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-1]
unknown: 
Command completed successfully
on:      t[0-1]
off:     
unknown: 
on:      
off:     t[0-1]
unknown: 
Command completed successfully
on:      t[0-1]
off:     
unknown: 
Command completed successfully
on:      
off:     t[0-1]
unknown: 
t0: 032
t1: 032
