#!/bin/sh
TEST=t53
$PATH_POWERMAND -f -c ${TEST_BUILDDIR}/$TEST.conf >$TEST.out 2>&1
test $? = 1 || exit 1
sed -i -e 's! [^: ]*t53\.dev! t53.dev!' $TEST.out
diff $TEST.out ${TEST_SRCDIR}/$TEST.exp >$TEST.diff
