#!/bin/sh
TEST=t54
#$PATH_POWERMAND -f -c $TEST.conf >$TEST.out 2>&1

$PATH_POWERMAN -Y -S $PATH_POWERMAND -C $TEST.conf \
    -q  widow-mds1 >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out $TEST.exp >$TEST.diff
