#!/bin/sh
TEST=t55
#$PATH_POWERMAND -f -c ${TEST_BUILDDIR}/$TEST.conf >$TEST.out 2>&1

$PATH_POWERMAN -Y -S $PATH_POWERMAND -C ${TEST_BUILDDIR}/$TEST.conf \
    -q corn2 >$TEST.out 2>$TEST.err
test $? = 0 || exit 1
diff $TEST.out ${TEST_SRCDIR}/$TEST.exp >$TEST.diff
