#!/bin/sh
# check stonith script with aliased plugs

TEST=t57

PM_SIMSTATE=$(mktemp) || exit 1
export PM_SIMSTATE

PM_OVERRIDE="${TEST_SRCDIR}/pm-sim -A"
export PM_OVERRIDE

PM_VERBOSE=1
export PM_VERBOSE

$PATH_POWERMAN_STONITH on t >$TEST.out 2>&1
test $? = 0 || exit 1
$PATH_POWERMAN_STONITH off t >>$TEST.out 2>&1
test $? = 0 || exit 1
rm -f $PM_SIMSTATE
sed -i -e 's/ [^ ]*pm-sim/ pm-sim/g' $TEST.out
diff $TEST.out ${TEST_SRCDIR}/$TEST.exp >$TEST.diff
