#!/bin/sh
# check stonith script with single plug that fails off

TEST=t58

PM_SIMSTATE=$(mktemp) || exit 1
export PM_SIMSTATE

PM_OVERRIDE="./pm-sim"
export PM_OVERRIDE

PM_VERBOSE=1
export PM_VERBOSE

$PATH_POWERMAN_STONITH on t >$TEST.out 2>&1
test $? = 0 || exit 1
PM_OVERRIDE="./pm-sim -r -s -t"
$PATH_POWERMAN_STONITH off t >>$TEST.out 2>&1
test $? = 1 || exit 1
rm -f $PM_SIMSTATE
diff $TEST.out $TEST.exp >$TEST.diff
