#!/bin/bash

# heartbeat STONITH module for powerman

PATH=/bin:/usr/sbin:$PATH

#ha_logger -t heartbeat "powerman stonith agent called with args: $*"

export pm_verbose=1

pmlog () {
	[ $pm_verbose == 1 ] && logger -t heartbeat "powerman-stonith: $*"
}

# N.B. agent must not exit 0 if the target is still on! (chaos bz 1439)
# Heartbeat will retry if we fail (don't retry here)
pmoff () {
	local plug=$1
	local state rc

	pm -h $serverhost -0 $plug
	rc=$?
	pmlog "pm -h $serverhost -0 $plug, rc=$rc"
	if [ $rc == 0 ]; then
		state=$(pm -h $serverhost -qx $plug | awk '{ print $NF }')
		[ "$state" == "off" ] || rc=1
		pmlog "pm -h $serverhost -q $plug, state=$state, rc=$rc"
	fi
	return $rc  # 0=success
}

pmon () {
	local plug=$1
	local rc

	pm -h $serverhost -1 $plug
	rc=$?
	pmlog "pm -h $serverhost -1 $plug, rc=$rc"
	return $rc  # 0=success
}

pmcycle () {
	local plug=$1
	local rc

	pm -h $serverhost -c $plug
	rc=$?
	pmlog "pm -h $serverhost -c $plug, rc=$rc"
	return $rc  # 0=success
}

case $1 in
gethosts)
	exec pm -h $serverhost -lx
	;;
on)
	pmon $2
	exit $?
	;;
off)
	pmoff $2
	exit $?
	;;
reset)
	if [ "$poweroff" == "1" ]; then
		pmoff $2
		exit $?
	else
		pmcycle $2
		exit $?
	fi
	;;
status)
	exec pm -h $serverhost -l >/dev/null
	;;
getconfignames)
	echo serverhost
	echo poweroff
	exit 0
	;;
getinfo-devid|getinfo-devname|getinfo-devdescr)
	echo "powerman STONITH device"
	exit 0
	;;
getinfo-devurl)
	echo "http://powerman.sourceforge.net/"
	exit 0
	;;
getinfo-xml)
	cat <<PMEOL
<parameters>
 <parameter name="serverhost" unique="1" required="1">
  <content type="string" default="localhost:10101"/>
  <shortdesc lang="en">host:port of powerman server</shortdesc>
  <longdesc lang="en">
  Specify the host:port of the powerman server, e.g. pmserver:10101
  </longdesc>
 </parameter>

 <parameter name="poweroff" unique="0" required="0">
  <content type="string" default="0"/>
  <shortdesc lang="en">Power off when given reset command</shortdesc>
  <longdesc lang="en">
  For V1 heartbeat which always resets to fence, power off when given
  the reset command.
  </longdesc>
 </parameter>
</parameters>
PMEOL
	exit 0
	;;
*)
	exit 1
	;;
esac
