# do not check code copied into the project
# do not check sha code, lots of hashing false positives
# do not check testing data
[files]
extend-exclude = [
  "config/*",
  "src/liblsd/*",
  "t/sharness.sh",
  "t/t0000-sharness.sh",
  "t/aggregate-results.sh",
]

[default.extend-words]
# commonly used names/variables that aren't typos
SER = "SER"
admn = "admn"

