# do not check code copied into the project
# do not check sha code, lots of hashing false positives
# do not check testing data
[files]
extend-exclude = [
  "config/*",
  "src/liblsd/*",
]

[default.extend-words]
# commonly used names/variables that aren't typos
SER = "SER"
admn = "admn"

