#!/bin/sh
####################################################################
# $Id$
# by Andrew C. Uselton <uselton2@llnl.gov> 
# Copyright (C) 2000 Regents of the University of California
# See ../DISCLAIMER
# v. 0-0-1:  2001-07-11
# v. 0-0-2:  2001-07-31
####################################################################
USERID=`id -u`
if [ ! "X$USERID" = "X0" ]
then
    echo "You must be root to run this"
    exit
fi

while [ 1 ]
do
  clustermon $*
  sleep 1
done
