#!/usr/bin/perl
#
# Call to the ES40Power package's do_reset() function in es40_powerlib.pl
# Usage: es40_reset host [host...]
# adapted from the original "api_reset" of
# Jim Garlick 2/15/01
# by
# Andrew Uselton 6/5/01
#
use strict;

# might want to put a path in here
require "es40_powerlib.pl";

use vars qw($node $val $EXITERROR $EXITOK $ON $OFF);
my ($node, $val, $EXITERROR, $EXITOK, $ON, $OFF);

$EXITERROR = 1;
$EXITOK    = 0;
$ON        = 1;
$OFF       = 0;


if (!@ARGV) {
    printf STDERR ("Usage: es40_reset node [node...]\n");
    exit($EXITERROR);
}	

ES40Power::es40_power_init(@ARGV);

foreach $node (@ARGV) {
	printf ("Resetting node $node\n");
	$val = es40Power::do_reset($node);
	if ($val == $OFF)
	{ 
	    printf("Error: Node %s is not ON!\n", $node);
	    exit($EXITERROR);
	}
}
exit($EXITOK);

