#!/bin/bash
VERSION="powerman-0.1"
DOC="/usr/doc/$VERSION"
LIB="/usr/lib/powerman"
ETC="/etc"
BIN="/usr/bin"
if [ $UID -ne 0 ]
then
  echo "You must be root to run this!"
  exit
fi
if [ -f README -a \
     -f check -a \
     -f clustermon -a \
     -f clusterview -a \
     -f ether-wake -a \
     -f powerman -a \
     -d etc -a \
     -f etc/powerman.conf -a \
     -d lib -a \
     -f lib/powerlib.tcl -a \
     -f lib/alpha.exp -a \
     -f lib/ditty_check -a \
     -f lib/console.gif -a \
     -f lib/cs20_off.gif -a \
     -f lib/cs20_on.gif -a \
     -f lib/es40_off.gif -a \
     -f lib/es40_on.gif -a \
     -f lib/tux_off.gif -a \
     -f lib/tux_on.gif -a \
     -f lib/up2000_off.gif -a \
     -f lib/up2000_on.gif -a \
     -d $ETC -a \
     -d $BIN \
]
then
  echo "Files and directories look okay.  Proceeding ..."
else
  echo "Missing files.  Is this the correct directory?  Do you need to make etherwake?"
  exit
fi
if [ ! -d $DOC ]
then
  echo "Creating directory $DOC"
  mkdir $DOC
  if [ ! -d $DOC ]
  then
    echo "Couldn't create doc directory $DOC"
    exit
  else
    MAKDEDOC="TRUE"
  fi
fi
if [ ! -d $LIB ]
then
  echo "Creating directory $LIB"
  mkdir $LIB
  if [ ! -d $LIB ]
  then
    echo "Couldn't create lib directory $LIB"
    if [ ! "X$MADEDOC" = "X" ]
    then
      echo "Removing doc directory $DOC"
      rmdir $DOC
    fi
    exit
  fi
fi
echo "copy README to $DOC"
cp README $DOC

echo "copy check to $BIN"
cp check $BIN
echo "copy clustermon to $BIN"
cp clustermon $BIN
echo "copy clusterview to $BIN"
cp clusterview $BIN
echo "copy powerman to $BIN"
cp powerman $BIN

echo "copy etc/powerman.conf to $ETC"
cp etc/powerman.conf $ETC

echo "copy lib/powerlib.tcl to $LIB"
cp lib/powerlib.tcl $LIB
echo "copy lib/alpha.exp to $LIB"
cp lib/alpha.exp $LIB
echo "copy lib/ditty_check to $LIB"
cp lib/ditty_check $LIB
echo "copy lib/console.gif to $LIB"
cp lib/console.gif $LIB
echo "copy ether-wake to $LIB"
cp ether-wake $LIB
echo "copy lib/cs20_off.gif to $LIB"
cp lib/cs20_off.gif $LIB
echo "copy lib/cs20_on.gif to $LIB"
cp lib/cs20_on.gif $LIB
echo "copy lib/es40_off.gif to $LIB"
cp lib/es40_off.gif $LIB
echo "copy lib/es40_on.gif to $LIB"
cp lib/es40_on.gif $LIB
echo "copy lib/tux_off.gif to $LIB"
cp lib/tux_off.gif $LIB
echo "copy lib/tux_on.gif to $LIB"
cp lib/tux_on.gif $LIB
echo "copy lib/up2000_off.gif to $LIB"
cp lib/up2000_off.gif $LIB
echo "copy lib/up2000_on.gif to $LIB"
cp lib/up2000_on.gif $LIB


