#!/usr/bin/perl
#
# Call to the Power package's do_off() function in powerlib.pl
# Usage: slc_off host [host...]
# Andrew Uselton 6/5/01
#
use strict;

# might want to put a path in here
require "powerlib.pl";

use vars qw($node $val $EXITERROR $EXITOK $ON $OFF);
my ($node, $val, $EXITERROR, $EXITOK, $ON, $OFF);

$EXITERROR = 1;
$EXITOK    = 0;
$ON        = 1;
$OFF       = 0;

if (!@ARGV) {
    printf STDERR ("Usage: es40_off node [node...]\n");
    exit($EXITERROR);
}	

Power::power_init(@ARGV);

printf ("Turning off node(s) @ARGV\n");
$val = Power::do_off($node);
if ($val == $OFF)
{ 
    printf("Error: Node %s is already OFF\n", $node);
    exit($EXITERROR);
}
Power::power_fin();
exit($EXITOK);

