#!/bin/bash
cur_dir=`pwd`
DIR="/home/auselton/src/powerman"
cd $DIR
while [ -f DOIT ]
do
  $DIR/slc_stat slc0 slc1 slc2 slc3 slc4 slc5 slc6 slc8 slc9 slc10 slc11 slc12 slc13 slc14 slc15
  sleep 1
done
cd $cur_dir
