#!/usr/bin/perl
#
# Call to the Power package's do_on() function in powerlib.pl
# Usage: slc_on host [host...]
# Andrew Uselton 6/15/01
#
use strict;

# might want to put a path in here
require "powerlib.pl";

use vars qw($node $val $EXITERROR $EXITOK $ON $OFF);
my ($node, $val, $EXITERROR, $EXITOK, $ON, $OFF);

$EXITERROR = 1;
$EXITOK    = 0;
$ON        = 1;
$OFF       = 0;

if (!@ARGV) {
    printf STDERR ("Usage: es40_on node [node...]\n");
    exit($EXITERROR);
}

Power::power_init(@ARGV);

printf ("Turning on node(s) @ARGV\n");
$val = Power::do_on(@ARGV);
if ($val == $ON)
{ 
    printf("Error: One or more of the nodes is already ON\n");
    exit($EXITERROR);
}
Power::power_fin();
exit($EXITOK);

