#!/usr/bin/perl
#
# Call to the Power package's node_on() function in powerlib.pl
# Usage: slc_check host [host...]
# only the status of the last host is reported via the exit code
# Andrew Uselton 6/15/01
#
use strict;

# might want to put a path in here
require "powerlib.pl";

use vars qw($node $val $EXITERROR $EXITOK $ON $OFF $code);
my ($node, $val, $EXITERROR, $EXITOK, $ON, $OFF, $code);

$EXITERROR = 1;
$EXITOK    = 0;
$ON        = 1;
$OFF       = 0;
$code      = $EXITOK;

if (!@ARGV) {
    printf STDERR ("Usage: slc_check node [node...]\n");
    exit($EXITERROR);
}	

Power::power_init(@ARGV);

# Remember that "is_on" follows the usual C programming convention with 
# 1 == "True" or "Is on" and 0 == "False"
# The shell convention is the reverse with 0 == "True" or "successfull
# completion" and 1 == "False" or "error condition"

$val = Power::nodes_on(@ARGV);
if ($val == $ON)
{ 
    printf("All the nodes appear to be ON\n");
}
else
{
    printf("Some node (at least one) appears to be OFF\n");
    $code = $EXITERROR;
}
Power::power_fin();
exit($code);

