#!/bin/bash
VERSION="powerman-0.1"
DOC="/usr/doc/$VERSION"
LIB="/usr/lib/powerman"
ETC="/etc"
BIN="/usr/bin"
if [ $UID -ne 0 ]
then
  echo "You must be root to run this!"
  exit
fi
echo "Removing directory $DOC and its contents"
rm -Rf $DOC
echo "Removing directory $LIB and its contents"
rm -Rf $LIB
echo "Removing $BIN/check"
rm -f $BIN/check
echo "Removing $BIN/clustermon"
rm -f $BIN/clustermon
echo "Removing $BIN/clusterview"
rm -f $BIN/clusterview
echo "Removing $BIN/powerman"
rm -f $BIN/powerman
echo "Removing $ETC/powerman.conf"
rm -f $ETC/powerman.conf


