#!/usr/bin/perl
#
# Call to the UP2000Power package's do_off() function in up2000_powerlib.pl
# Usage: up2000_off host [host...]
# adapted from the original "api_reset" of
# Jim Garlick 2/15/01
# by
# Andrew Uselton 6/5/01
#
use strict;

# might want to put a path in here
require "up2000_powerlib.pl";

use vars qw($node $val $EXITERROR $EXITOK $ON $OFF);
my ($node, $val, $EXITERROR, $EXITOK, $ON, $OFF);

$EXITERROR = 1;
$EXITOK    = 0;
$ON        = 1;
$OFF       = 0;


if (!@ARGV) {
    printf STDERR ("Usage: up2000_off node [node...]\n");
    exit($EXITERROR);
}	

UP2000Power::up2000_power_init(@ARGV);

foreach $node (@ARGV) {
	printf ("Turning off node $node\n");
	$val = UP2000Power::do_off($node);
	if ($val == $OFF)
	{ 
	    printf("Error: Node %s is already OFF\n", $node);
            exit($EXITERROR);
	}
}
exit($EXITOK);

