name: ci

on: [ pull_request, push ]

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        cc: [gcc, clang]
        os: [ubuntu-latest, ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
            libsnmp-dev \
            libwrap0-dev \
            libcurl4-gnutls-dev \
            libgenders0-dev \
            libjansson-dev \
            automake \
            autoconf \
            pkg-config \
            ${{matrix.cc}}
    - name: Display configuration
      run: |
        echo "C compiler:"
        ${CC} --version
      env:
        CC: ${{matrix.cc}}
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: |
        ./configure \
           --with-genders \
           --with-snmppower \
           --with-httppower \
           --with-redfishpower \
           --with-tcp-wrappers
    - name: make
      run: make
    - name: GITHUB_CI=t make check
      run: make check
    - name: make distcheck
      run: DISTCHECK_CONFIGURE_FLAGS=--with-redfishpower make distcheck

  spelling:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Check Spelling
      uses: crate-ci/typos@e477391cc0243daaeeb154a7bfa67cb7d6fc5831 # v1.16.8
